from tkinter import*

global x
global y

x = y = 2

def derecha():

    global x
    global y

    x = x + 1

    b1=Button(ventana,bg="black")
    b2=Button(ventana,bg="black")
    b3=Button(ventana,bg="black")
    b4=Button(ventana,bg="black")
    b5=Button(ventana,bg="black")
    b6=Button(ventana,bg="black")
    b7=Button(ventana,bg="black")
    b8=Button(ventana,bg="black")
    b9=Button(ventana,bg="black")
    b10=Button(ventana,bg="black")
    b11=Button(ventana,bg="black")
    b12=Button(ventana,bg="black")
    b13=Button(ventana,bg="black")
    b14=Button(ventana,bg="black")
    b15=Button(ventana,bg="black")
    b16=Button(ventana,bg="black")
    b17=Button(ventana,bg="black")
    b18=Button(ventana,bg="black")
    b19=Button(ventana,bg="black")
    b20=Button(ventana,bg="black")
    b21=Button(ventana,bg="black")
    b22=Button(ventana,bg="black")
    b23=Button(ventana,bg="black")
    b24=Button(ventana,bg="black")
    b25=Button(ventana,bg="black")
    b1.grid(column=0,row=0)
    b2.grid(column=1,row=0)
    b3.grid(column=2,row=0)
    b4.grid(column=3,row=0)
    b5.grid(column=4,row=0)
    b6.grid(column=0,row=1)
    b7.grid(column=1,row=1)
    b8.grid(column=2,row=1)
    b9.grid(column=3,row=1)
    b10.grid(column=4,row=1)
    b11.grid(column=0,row=2)
    b12.grid(column=1,row=2)
    b13.grid(column=2,row=2)
    b14.grid(column=3,row=2)
    b15.grid(column=4,row=2)
    b16.grid(column=0,row=3)
    b17.grid(column=1,row=3)
    b18.grid(column=2,row=3)
    b19.grid(column=3,row=3)
    b20.grid(column=4,row=3)
    b21.grid(column=0,row=4)
    b22.grid(column=1,row=4)
    b23.grid(column=2,row=4)
    b24.grid(column=3,row=4)
    b25.grid(column=4,row=4)

    if(x>4):

        x=4

    baux=Button(ventana,bg="Blue")
    baux.grid(column=x,row=y)

def izquierda():

    global x
    global y

    x = x - 1

    b1=Button(ventana,bg="black")
    b2=Button(ventana,bg="black")
    b3=Button(ventana,bg="black")
    b4=Button(ventana,bg="black")
    b5=Button(ventana,bg="black")
    b6=Button(ventana,bg="black")
    b7=Button(ventana,bg="black")
    b8=Button(ventana,bg="black")
    b9=Button(ventana,bg="black")
    b10=Button(ventana,bg="black")
    b11=Button(ventana,bg="black")
    b12=Button(ventana,bg="black")
    b13=Button(ventana,bg="black")
    b14=Button(ventana,bg="black")
    b15=Button(ventana,bg="black")
    b16=Button(ventana,bg="black")
    b17=Button(ventana,bg="black")
    b18=Button(ventana,bg="black")
    b19=Button(ventana,bg="black")
    b20=Button(ventana,bg="black")
    b21=Button(ventana,bg="black")
    b22=Button(ventana,bg="black")
    b23=Button(ventana,bg="black")
    b24=Button(ventana,bg="black")
    b25=Button(ventana,bg="black")
    b1.grid(column=0,row=0)
    b2.grid(column=1,row=0)
    b3.grid(column=2,row=0)
    b4.grid(column=3,row=0)
    b5.grid(column=4,row=0)
    b6.grid(column=0,row=1)
    b7.grid(column=1,row=1)
    b8.grid(column=2,row=1)
    b9.grid(column=3,row=1)
    b10.grid(column=4,row=1)
    b11.grid(column=0,row=2)
    b12.grid(column=1,row=2)
    b13.grid(column=2,row=2)
    b14.grid(column=3,row=2)
    b15.grid(column=4,row=2)
    b16.grid(column=0,row=3)
    b17.grid(column=1,row=3)
    b18.grid(column=2,row=3)
    b19.grid(column=3,row=3)
    b20.grid(column=4,row=3)
    b21.grid(column=0,row=4)
    b22.grid(column=1,row=4)
    b23.grid(column=2,row=4)
    b24.grid(column=3,row=4)
    b25.grid(column=4,row=4)

    if(x<0):

        x=0

    baux=Button(ventana,bg="Blue")
    baux.grid(column=x,row=y)

def arriba():

    global x
    global y

    y = y - 1

    b1=Button(ventana,bg="black")
    b2=Button(ventana,bg="black")
    b3=Button(ventana,bg="black")
    b4=Button(ventana,bg="black")
    b5=Button(ventana,bg="black")
    b6=Button(ventana,bg="black")
    b7=Button(ventana,bg="black")
    b8=Button(ventana,bg="black")
    b9=Button(ventana,bg="black")
    b10=Button(ventana,bg="black")
    b11=Button(ventana,bg="black")
    b12=Button(ventana,bg="black")
    b13=Button(ventana,bg="black")
    b14=Button(ventana,bg="black")
    b15=Button(ventana,bg="black")
    b16=Button(ventana,bg="black")
    b17=Button(ventana,bg="black")
    b18=Button(ventana,bg="black")
    b19=Button(ventana,bg="black")
    b20=Button(ventana,bg="black")
    b21=Button(ventana,bg="black")
    b22=Button(ventana,bg="black")
    b23=Button(ventana,bg="black")
    b24=Button(ventana,bg="black")
    b25=Button(ventana,bg="black")
    b1.grid(column=0,row=0)
    b2.grid(column=1,row=0)
    b3.grid(column=2,row=0)
    b4.grid(column=3,row=0)
    b5.grid(column=4,row=0)
    b6.grid(column=0,row=1)
    b7.grid(column=1,row=1)
    b8.grid(column=2,row=1)
    b9.grid(column=3,row=1)
    b10.grid(column=4,row=1)
    b11.grid(column=0,row=2)
    b12.grid(column=1,row=2)
    b13.grid(column=2,row=2)
    b14.grid(column=3,row=2)
    b15.grid(column=4,row=2)
    b16.grid(column=0,row=3)
    b17.grid(column=1,row=3)
    b18.grid(column=2,row=3)
    b19.grid(column=3,row=3)
    b20.grid(column=4,row=3)
    b21.grid(column=0,row=4)
    b22.grid(column=1,row=4)
    b23.grid(column=2,row=4)
    b24.grid(column=3,row=4)
    b25.grid(column=4,row=4)

    if(y<0):

        y=0

    baux=Button(ventana,bg="Blue")
    baux.grid(column=x,row=y)

def abajo():

    global x
    global y

    y = y + 1

    b1=Button(ventana,bg="black")
    b2=Button(ventana,bg="black")
    b3=Button(ventana,bg="black")
    b4=Button(ventana,bg="black")
    b5=Button(ventana,bg="black")
    b6=Button(ventana,bg="black")
    b7=Button(ventana,bg="black")
    b8=Button(ventana,bg="black")
    b9=Button(ventana,bg="black")
    b10=Button(ventana,bg="black")
    b11=Button(ventana,bg="black")
    b12=Button(ventana,bg="black")
    b13=Button(ventana,bg="black")
    b14=Button(ventana,bg="black")
    b15=Button(ventana,bg="black")
    b16=Button(ventana,bg="black")
    b17=Button(ventana,bg="black")
    b18=Button(ventana,bg="black")
    b19=Button(ventana,bg="black")
    b20=Button(ventana,bg="black")
    b21=Button(ventana,bg="black")
    b22=Button(ventana,bg="black")
    b23=Button(ventana,bg="black")
    b24=Button(ventana,bg="black")
    b25=Button(ventana,bg="black")
    b1.grid(column=0,row=0)
    b2.grid(column=1,row=0)
    b3.grid(column=2,row=0)
    b4.grid(column=3,row=0)
    b5.grid(column=4,row=0)
    b6.grid(column=0,row=1)
    b7.grid(column=1,row=1)
    b8.grid(column=2,row=1)
    b9.grid(column=3,row=1)
    b10.grid(column=4,row=1)
    b11.grid(column=0,row=2)
    b12.grid(column=1,row=2)
    b13.grid(column=2,row=2)
    b14.grid(column=3,row=2)
    b15.grid(column=4,row=2)
    b16.grid(column=0,row=3)
    b17.grid(column=1,row=3)
    b18.grid(column=2,row=3)
    b19.grid(column=3,row=3)
    b20.grid(column=4,row=3)
    b21.grid(column=0,row=4)
    b22.grid(column=1,row=4)
    b23.grid(column=2,row=4)
    b24.grid(column=3,row=4)
    b25.grid(column=4,row=4)

    if(y>4):

        y=4

    baux=Button(ventana,bg="Blue")
    baux.grid(column=x,row=y)

ventana = Tk()
ventana.geometry("350x350")

b1=Button(ventana,bg="black")
b2=Button(ventana,bg="black")
b3=Button(ventana,bg="black")
b4=Button(ventana,bg="black")
b5=Button(ventana,bg="black")
b6=Button(ventana,bg="black")
b7=Button(ventana,bg="black")
b8=Button(ventana,bg="black")
b9=Button(ventana,bg="black")
b10=Button(ventana,bg="black")
b11=Button(ventana,bg="black")
b12=Button(ventana,bg="black")
b13=Button(ventana,bg="black")
b14=Button(ventana,bg="black")
b15=Button(ventana,bg="black")
b16=Button(ventana,bg="black")
b17=Button(ventana,bg="black")
b18=Button(ventana,bg="black")
b19=Button(ventana,bg="black")
b20=Button(ventana,bg="black")
b21=Button(ventana,bg="black")
b22=Button(ventana,bg="black")
b23=Button(ventana,bg="black")
b24=Button(ventana,bg="black")
b25=Button(ventana,bg="black")
bd=Button(ventana,command=derecha)
bi=Button(ventana,command=izquierda)
bab=Button(ventana,command=arriba)
bar=Button(ventana,command=abajo)

b1.grid(column=0,row=0)
b2.grid(column=1,row=0)
b3.grid(column=2,row=0)
b4.grid(column=3,row=0)
b5.grid(column=4,row=0)
b6.grid(column=0,row=1)
b7.grid(column=1,row=1)
b8.grid(column=2,row=1)
b9.grid(column=3,row=1)
b10.grid(column=4,row=1)
b11.grid(column=0,row=2)
b12.grid(column=1,row=2)
b13.grid(column=2,row=2)
b14.grid(column=3,row=2)
b15.grid(column=4,row=2)
b16.grid(column=0,row=3)
b17.grid(column=1,row=3)
b18.grid(column=2,row=3)
b19.grid(column=3,row=3)
b20.grid(column=4,row=3)
b21.grid(column=0,row=4)
b22.grid(column=1,row=4)
b23.grid(column=2,row=4)
b24.grid(column=3,row=4)
b25.grid(column=4,row=4)
bd.grid(column=15,row=3)
bi.grid(column=13,row=3)
bab.grid(column=14,row=2)
bar.grid(column=14,row=4)
baux=Button(ventana,bg="Blue")
baux.grid(column=x,row=y)

ventana.mainloop()